name: 'Deploy Docker app'
description: 'Deploy the application's Docker Compose file'

inputs:
  docker-user:
    description: "Docker username"
    required: true
  docker-password:
    description: "Docker password"
    required: true
  image-name:
    description: "Complete image name to pull including version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Download Compose file
      uses: actions/download-artifact@v4
      with:
        name: docker
    
    - name: Docker Login
      shell: bash
      run: echo ${{ inputs.docker-password }} | docker login -u ${{ inputs.docker-version }} --password-stdin

    - name: Docker Pull
      shell: bash
      run: docker pull ${{ inputs.image-name }}

    - name: Docker Up
      shell: bash
      run: docker-compose --env-file .env -f ./docker/docker-compose.yaml up -d