version: "3"
services: 
  bot:
    build:
      dockerfile: ./src/SheepBot/Dockerfile
      context: .
      args:
        BUILD_MODE: ${BUILD_MODE:-Debug}
    image: ctartamella/sheepbot:latest
    container_name: sheepbot
    depends_on:
      - sqlserver
    environment:
      VERSION: ${VERSION}
      Sheepbot__ConnectionStrings__Default: ${ConnectionString}
      Sheepbot__iRacing__Email: ${IracingEmail}
      Sheepbot__iRacing__Password: ${IracingPassword}
      Sheepbot__Discord__GuildId: ${DiscordGuild}
      Sheepbot__Discord__Token: ${DiscordToken}
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - SA_PASSWORD=${DbPassword}
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - sql_data:/var/opt/mssql/data 
      - sql_logs:/var/opt/mssql/log
      - sql_secrets:/var/opt/mssql/secrets

volumes:
  sql_data:
  sql_logs:
  sql_secrets: