version: "3"
services: 
  bot:
    build:
      dockerfile: ./src/SheepBot/Dockerfile
      context: .
      args:
        BUILD_MODE: ${BUILD_MODE:-Debug}
    image: ctartamella/sheepbot:latest
    container_name: sheepbot
    depends_on:
      - sqlserver
    environment:
      VERSION: ${VERSION}
      SHEEPBOT__CONNECTIONSTRINGS__DEFAULT: ${ConnectionString}
      SHEEPBOT__IRACING__EMAIL: ${IracingEmail}
      SHEEPBOT__IRACING__PASSWORD: ${IracingPassword}
      SHEEPBOT__DISCORD__GUILDID: ${DiscordGuild}
      SHEEPBOT__DISCORD__TOKEN: ${DiscordToken}
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=${DbPassword}
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"