name: Deploy Database
description: Deploy the project DACPAC to the specified connection string

inputs:
  sa-password:
    description: System administrator password for the database
    required: true
  db-name:
    description: Name of the database to deploy to
    required: true
  db-host:
    description: Database server host name
    required: true
  path:
    description: Path for deployment resources
    required: true
    
runs:
  using: composite
  steps:
    - name: Download DACPAC
      uses: actions/download-artifact@v4
      with:
        path: ${{ inputs.path }}
        name: dacpac

    - name: Deploy DACPAC
      shell: bash
      run: sqlpackage /Action:Publish /SourceFile:${{ inputs.path }}/database.dacpac /TargetServerName:${{ inputs.db-host }} /TargetUser:sa /TargetPassword:${{ inputs.sa-password }} /TargetDatabaseName:${{ inputs.db-name }} /TargetTrustServerCertificate:True /p:DropObjectsNotInSource=true