name: Deploy Database
description: Deploy the project DACPAC to the specified connection string

inputs:
  connection-string:
    description: Connection string for the database
    required: true
  sa-password:
    required: true
  db-name:
    required: true
  db-host:
    required: true
  path:
    required: true
    
runs:
  using: composite
  steps:
    - name: Download DACPAC
      uses: actions/download-artifact@v4
      with:
        path: ${{ inputs.path }}
        name: dacpac

    - name: Install SQL tools
      uses: potatoqualitee/mssqlsuite@v1.7
      with:
        install: sqlclient, sqlpackage

    - name: Create DB
      shell: bash
      run: |
        echo 'IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = '${{ inputs.db-name }}')
              BEGIN
                  CREATE DATABASE ${{ inputs.db-name }}
              END' | sqlcmd -S ${{ inputs.db-host }} -U sa -P ${{ inputs.sa-password }} -d tempdb -i /dev/stdin

    - name: Deploy DACPAC
      shell: bash
      run: sqlpackage /Action:Publish /TargetConnectionString:${{ inputs.connection-string }} /SourceFile:${{ inputs.path }}/database.dacpac /p:DropObjectsNotInSource=true