name: Deploy Application
description: Deploy the application's code and infrastructure

inputs:
  environment:
    description: Environment name
    required: true
    default: DEV
  connection-string:
    description: Database connection string
    required: true
  image-name:
    description: Docker image name
    required: true
  discord-token:
    description: The bot token to be used for Discord
    required: true
  iracing-email:
    description: iRacing account email for API usage
    required: true
  iracing-password:
    descriptio: iRacing account password for API usage
    required: true
  db-host:
    description: The database server host name
    required: true
  db-name:
    description: The name of the database to deploy to
    required: true
  sa-password:
    description: The system administrator password for SQL server
    required: true
  docker-user:
    description: The username to use for Docker Hub
    required: true
  docker-password:
    description: The password used for Docker Hub
    required: true
  discord-webhook-id:
    description: The webhook ID used for Discord notifications
    required: true
  discord-webhook-token:
    description: The webhook password used for Discord notifications
    required: true
    
runs:
  using: composite
  steps:
    - name: Retrieve Version
      uses: ./.github/actions/retrieve-version
      id: version

    - name: Deploy Application
      uses: ./.github/actions/deploy-app
      with:
        path: ./deployment/sheepbot-dev
        docker-user: ${{ inputs.docker-user }}
        docker-password: ${{ inputs.docker-password }}
        image-name: ${{ inputs.image-name }}:${{ steps.version.outputs.version }}
        version: ${{ steps.version.outputs.version }}        
        environment: ${{ inputs.environment }}
        connection-string: ${{ inputs.connection-string }}
        iracing-email: ${{ inputs.iracing-email }}
        iracing-password: ${{ inputs.iracing-password }}
        discord-token: ${{ inputs.discord-token }}
        sa-password: ${{ inputs.sa-password }}

    - name: Deploy Database
      uses: ./.github/actions/deploy-database
      with:
        path: ./deployment/database
        db-host: ${{ inputs.db-host }}
        db-name: ${{ inputs.db-name }}
        sa-password: ${{ inputs.sa-password }}

    - name: Notify Discord
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ inputs.discord-webhook-id }}
        webhook_token: ${{ inputs.discord-webhook-token }}
        args: ${{ inputs.environment }} deployment complete.