name: Deploy Docker app
description: Deploy the application's Docker Compose file
inputs:
  environment:
    description: Environment name
    required: true
    default: DEV
  connection-string:
    required: true
  image-name:
    required: true
  discord-token:
    required: true
  iracing-email:
    required: true
  iracing-password:
    required: true
  db-host:
    required: true
  db-name:
    required: true
  sa-password:
    required: true
  docker-user:
    description: The username to use for Docker Hub
    required: true
  docker-password:
    description: The password used for Docker Hub
    required: true
  discord-webhook-id:
    description: The webhook used for Discord notifications
    required: true
  discord-webhook-token:
    description: The webhook used for Discord notifications
    required: true
runs:
  using: composite
  steps:
    - name: Retrieve Version
      uses: ./.github/actions/retrieve-version
      id: version

    - name: Deploy Docker
      uses: ./.github/actions/deploy-app
      with:
        path: ./deployment/sheepbot-dev
        docker-user: ${{ inputs.docker-user }}
        docker-password: ${{ inputs.docker-password }}
        image-name: ${{ inputs.image-name }}:${{ steps.version.outputs.version }}
        version: ${{ steps.version.outputs.version }}        
        environment: ${{ inputs.environment }}
        connection-string: ${{ inputs.connection-string }}
        iracing-email: ${{ inputs.iracing-email }}
        iracing-password: ${{ inputs.iracing-password }}
        discord-token: ${{ inputs.discord-token }}
        sa-password: ${{ inputs.sa-password }}

    - name: Deploy Database
      uses: ./.github/actions/deploy-database
      with:
        path: ./deployment/database
        db-host: ${{ inputs.db-host }}
        db-name: ${{ inputs.db-name }}
        sa-password: ${{ inputs.sa-password }}

    - name: Notify Discord
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ inputs.discord-webhook-id }}
        webhook_token: ${{ inputs.discord-webhook-token }}
        args: ${{ inputs.environment }} deployment complete.