name: Deploy Application
description: Deploy the application's Docker Compose file

inputs:
  path:
    description: Path for deployment artifacts
    required: true
  docker-user:
    description: Docker username
    required: true
  docker-password:
    description: Docker password
    required: true
  image-name:
    description: Complete image name to pull including version
    required: true
  version:
    description: The tag of the image to pull
    required: true
  environment:
    description: The environment name
    required: true
  connection-string:
    description: The connection string to the application database
    required: true
  iracing-email:
    description: iRacing username
    required: true
  iracing-password:
    description: iRacing password
    required: true
  discord-token:
    description: Discord bot token
    required: true
  sa-password:
    required: true
    
runs:
  using: composite
  steps:
    - name: Populate Environment
      shell: bash
      run: |
        rm -f .env
        touch .env
        echo "VERSION=${{ inputs.version }}" >> .env
        echo "ENVIRONMENT=${{ inputs.environment }}" >> .env
        echo "CONNECTION=${{ inputs.connection-string}}" >> .env
        echo "IRACINGEMAIL=${{ inputs.iracing-email }}" >> .env
        echo "IRACINGPASSWORD=${{ inputs.iracing-password }}" >> .env
        echo "DISCORDTOKEN=${{ inputs.discord-token }}" >> .env
        echo "SAPASSWORD=${{ inputs.sa-password }}" >> .env
        mkdir --parents ${{ inputs.path }}/; mv .env $_
        
    - name: Download Compose file
      uses: actions/download-artifact@v4
      with:
        path: ${{ inputs.path }}
        name: docker
    
    - name: Docker Login
      shell: bash
      run: echo ${{ inputs.docker-password }} | docker login -u ${{ inputs.docker-user}} --password-stdin

    - name: Docker Pull
      shell: bash
      run: docker pull ${{ inputs.image-name }}

    - name: Docker Up
      shell: bash
      run: docker-compose --env-file ${{ inputs.path }}/.env -f ${{ inputs.path }}/docker-compose.yaml up -d