name: Database

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch: 

jobs:
  build :
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      
      - name: Build DACPAC
        run: msbuild /p:TargetFrameworkVersion=v4.7.2 ${{ github.workspace }}/database/database.sqlproj

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dacpac
          path: ${{ github.workspace }}/database/bin/Debug/
