name: Application

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch: 

jobs:
  compute-version:
    name: Compute Version
    runs-on: [self-hosted, build]
    steps:
      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          version_format: "${major}.${minor}.${patch}-pre${increment}"

      - name: Store version
        run: echo ${{ steps.version.outputs.version }} >> version
      
      - uses: actions/upload-artifact@v4
        with:
          name: version
          path: version

  build-db:
    name: Build Database
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      
      - name: Build DACPAC
        run: msbuild /p:TargetFrameworkVersion=v4.7.2 ${{ github.workspace }}/database/database.sqlproj

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dacpac
          path: ${{ github.workspace }}/database/bin/Debug/

  build-app:
    name: Build App
    runs-on: [ self-hosted, build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: .github/workflows/actions/retrieve-version.yml
        name: Retrieve Version

      - name: Build and Push
        uses:  mr-smithers-excellent/docker-build-push@v6.2
        with:
          image: "ctartamella/sheepbot"
          dockerfile: "./src/SheepBot/Dockerfile"
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          tags: ${{ steps.version.outputs.version }}
          buildArgs: BUILD_MODE=Release
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker
          path: docker-compose.yaml

  deploy-dev:
    name: Deploy Dev
    runs-on: [self-hosted, dev]
    environment: DEV
    needs: [ build-app, build-db ]
    steps:      
      - uses: ./.github/workflows/actions/retrieve-version
        name: Retrieve Version

      - uses: actions/download-artifact@v4
        with:
          name: dacpac
      
      - uses: actions/download-artifact@v4
        with:
          name: docker

      - name: Populate Environment
        run: |
          rm .env
          touch .env
          echo "${{ secrets.ENV_FILE }}" >> .env
          echo "VERSION=${{ env.VERSION }}" >> .env
          echo "ENVIRONMENT=dev" >> .env

      - name: Deploy Database Schema
        uses: azure/sql-action@v2.2.1
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './dacpac/database.dacpac'
          action: 'publish'
          arguments: '/p:DropObjectsNotInSource=true'  

      - name: Docker Pull
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker pull ctartamella/sheepbot:${{ env.VERSION }}

      - name: Docker Up
        run: docker-compose --env-file .env -f ./docker/docker-compose.yaml up -d

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Dev deployment complete.'
