name: Container Build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch: 

jobs:

  build:
    name: Build Sync Host
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
         debug: true
         version_format: "${major}.${minor}.${patch}-pre${increment}"
  
      - name: Build and Push
        uses:  mr-smithers-excellent/docker-build-push@v4
        with:
          image: "ctartamella/sheepbot"
          dockerfile: "./src/SheepBot/Dockerfile"
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          tag: ${{ steps.version.outputs.version }}

  deploy:
    name: Deploy Dev
    runs-on: [self-hosted, dev]
    environment: DEV
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Populate Environment
        run: echo "${{secrets.ENV_FILE }}\nVERSION=${{ steps.version.outputs.version }}" > .env && echo

      - name: Docker Up
        run: docker-compose --env-file .env -f docker-compose.yml up -d --build
